### ISSUE TITLE
CRAN version saves only audio, remotes from github version returns error

### ISSUE THREAD

**Issue by avakiai** [maRce10/dynaSpec#15]
Hi there, 

I'm very keen to use dynaSpec to show some spectrograms along with some video we have of bats socializing. However, I'm having issues getting dynaSpec up and running. 

I'm on a Windows 11 machine and I've installed FFMPEG via this [link](https://github.com/BtbN/FFmpeg-Builds/releases) (namely, I installed the build [ffmpeg-master-latest-win64-gpl.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip)). 

If I load dynaSpec after installing from CRAN, I get the following error when I try to run your example:

```
data("canyon_wren")
scrolling_spectro(wave = canyon_wren, wl = 300, 
                  t.display = 1, pal = viridis, 
                  grid = FALSE, flim = c(1, 9), 
                  width = 1000, height = 500, res = 120, 
                  file.name = "black.mp4", colbg = "black")

Returns:
Warning messages:
1: In system(cll1, intern = TRUE, ignore.stdout = TRUE, ignore.stderr = TRUE) :
  running command 'ffmpeg -framerate 50 -i C:\Users\AVAKIA~1\AppData\Local\Temp\RtmpmcHk6L/%05d.temp.img.tiff -c:v libx264 -profile:v high -crf 2 -pix_fmt yuv420p -y C:\Users\AVAKIA~1\AppData\Local\Temp\RtmpmcHk6L/scroll.spectro.temp.mp4' had status 69
2: In graphics::par(opar) : graphical parameter "cin" cannot be set
3: In graphics::par(opar) : graphical parameter "cra" cannot be set
4: In graphics::par(opar) : graphical parameter "csi" cannot be set
5: In graphics::par(opar) : graphical parameter "cxy" cannot be set
6: In graphics::par(opar) : graphical parameter "din" cannot be set
7: In graphics::par(opar) : graphical parameter "page" cannot be set
```
An .mp4 file is then opened/saved that contains the audio but no video.

I tried re-installing dynaSpec from github via remotes. Now when I try to run the example, nothing is created or saved, and instead I get the error: 

```
Error in checkCluster(cl) : not a valid cluster
```

Any suggestions for how to get around the errors in either case? 

Thanks!

My ffmpeg install version:
```
C:\Users\Ava Kiai>ffmpeg -version
ffmpeg version N-108709-g3bd0bf76fb-20221017 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20221017
libavutil      57. 39.101 / 57. 39.101
libavcodec     59. 50.101 / 59. 50.101
libavformat    59. 34.101 / 59. 34.101
libavdevice    59.  8.101 / 59.  8.101
libavfilter     8. 49.101 /  8. 49.101
libswscale      6.  8.112 /  6.  8.112
libswresample   4.  9.100 /  4.  9.100
libpostproc    56.  7.100 / 56.  7.100

```

**Comment by avakiai** [comment]
Update: 

I tried to generated a paged spectrogram/Matt's approach, following the example for the barn owls. 
The sample data runs correctly. When I try to run my data, it also looks ok up until the final step, where it seems it cannot handle a sampling rate of 250000. I can downsample my data, though that would also mean the frequency composition would change...: 
```
> params <-prep_static_ggspectro(dat,destFolder="wd",savePNG=T)
> bats<- prep_static_ggspectro(dat,destFolder=tempdir(),savePNG=T,onlyPlotSpec = F)
> paged_spectro(bats)
Temporary files saved at: C:\Users\AVAKIA~1\AppData\Local\Temp\RtmpqS8Obu/temp/
Saved temp wav segment: C:\Users\AVAKIA~1\AppData\Local\Temp\RtmpqS8Obu/temp/group2_session1_silence_1563-1573s_1_.wav
Saved temp wav segment: C:\Users\AVAKIA~1\AppData\Local\Temp\RtmpqS8Obu/temp/group2_session1_silence_1563-1573s_2_.wav[1] "Spec saved @ C:\\Users\\AVAKIA~1\\AppData\\Local\\Temp\\RtmpqS8Obu/temp/group2_session1_silence_1563-1573s_1_.png"
using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512                                                    
profile High, level 6.0, 4:2:0, 8-bit
264 - core 161 r3053M c347e7a - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Specified sample rate 250000 is not supported
Error: FFMPEG error in 'avcodec_open2 (audio)': Invalid argument
```

**Comment by tomwebber96** [comment]
I'm also having the same issue as avakiai. I have called Sys.which('ffmpeg') within the R console to check R can find the install of ffmpegand it does. I also get a .mp4 file which only conatins audio.

**Comment by drwilkins** [comment]
Hi Ava, sorry for the delay, I don't really have a lot of time for package support anymore. This was a side project during my postdoc.

I think you'll likely have to resample your WAV files for visualization purposes. I developed my functions for the package with whale and birdsong and haven't tried with any crazy bat ultrasonic signals :) 

Tom, for issues with Marcelo's functions, you might have better luck emailing him directly. You should find his email on his website here: https://marceloarayasalas.weebly.com/. Sorry I can't be more help at this time, and thanks for checking out dynaSpec!

**Comment by maRce10** [comment]
sorry for the delay in responding. I think the cluster issue has been fixed in the latest version. Please re-install it from github and try again. Let me know if that works.

**Comment by Pegasus1106** [comment]
Hii maRce10,
I am suffering with the issue:

Error in checkCluster(cl) : not a valid cluster

**Comment by KatrinaWilcox** [comment]
Hello,
I am having the same issue as above (Error in checkCluster(cl): not a valid cluster) after installing the latest version from github.

**Comment by maRce10** [comment]
I fixed the bug. I have also created a google colab notebook that can be used to make dynaSpec videos. I think this can be a better option as the installation of external dependencies can be a pain in the butt. This is link to the notebook:

https://colab.research.google.com/drive/1t3Wn9OifcZTvxOMVNmz9dF25vnzU3_Fr?usp=sharing
