### ISSUE TITLE
audio sampling rate of 48000 or maybe more might be a problem in the final video's audio

### ISSUE THREAD

**Issue by eldertiger** [maRce10/dynaSpec#16]
**Describe the bug**
The audio in this video(https://www.youtube.com/watch?v=OxvKoPyX-4o) is different from originial xeno-canto audio although the visualization is right. 
After some test, I found out downsample of audio in R language package including packages _seewave_ , and _av_ (fucntion _resamp_ and _downsample_)is not generating correct result like a resampling in software Audacity. Oversample seems to be ok  as the screenshot below.

**To Reproduce**
Here is the code I used to check audio resample functions of R packages, you can check the spectrom after resample or video output using Audacity as the attached screenshot. There are a lot of echoes( disturbance? I don't know how to describe this phenomenon) in all the frequencies. _ffmpeg_ does degrade the input audio( some missing in the spectrogram compare to original audio ) but it should have nothing to do with this problem. This seems to be R package problem.

```
library('monitoR')#for better MP3 slicing, the read_wave or TuneR's readWave can't slice mp3 files, they just read the whole file into the wav variable.
ngh_wren <- readMP3(filename = "Nightingale-Wren.mp3", from = 1, to = 3) #https://xeno-canto.org/518334
ngh_wren_44100_downsample <- downsample(ngh_wren, 44100)
ngh_wren_44100 <- resamp(ngh_wren,f=48000, g=44100, channel = 1, output="Wave")
ngh_wren_96000 <- resamp(ngh_wren,f=48000, g=96000, channel = 1, output="Wave")
ngh_wren_48000 <- resamp(ngh_wren_44100,f=44100,  g=48000, channel = 1, output="Wave")
print(ngh_wren)
print(ngh_wren_44100_downsample)
savewav(ngh_wren, filename = "ngh_wren_orginal.wav")
savewav(ngh_wren_44100_downsample, filename = "ngh_wren_44100_downsample.wav")
savewav(ngh_wren_44100, filename = "ngh_wren_44100_resamp.wav")
savewav(ngh_wren_48000, filename = "ngh_wren_48000_resamp_from_44100.wav")
savewav(ngh_wren_96000, filename = "ngh_wren_96000_resamp.wav")

scrolling_spectro(wave = ngh_wren, wl = 300, 
              t.display = 3, pal = viridis, 
              grid = FALSE, flim = c(0.1, 9), 
              width = 1080, height =720, fps=24,collevels = seq(-100, 0, 1),
              res = 72, file.name = "ngh_wren_orginal.mp4",,colbg = "black",
              osc = TRUE,colwave = "#03bef7d1")# video's audio is damaged as the screenshot below
ngh_wren_original_44100_audacity <- read_wave("ngh_wren_original_44100_audacity.wav") # resample originial audio to 44100 using Audacity
print(ngh_wren_original_44100_audacity)
scrolling_spectro(wave = ngh_wren_original_44100_audacity, wl = 512, 
              t.display = 3, pal = viridis, 
              grid = FALSE, flim = c(0.1, 9), 
              width = 1080, height =720, fps=24,collevels = seq(-100, 0, 1),
              res = 72, file.name = "ngh_wren_original_44100_audacity.mp4",,colbg = "black",
              osc = TRUE,colwave = "#03bef7d1")# final video will have the right audio now.
``` 

**Screenshots**
![resample_issue_of_R](https://user-images.githubusercontent.com/22476172/232965827-70fd88ee-0396-4135-9027-64539129e601.PNG)

**Additional context**
I wonder if it's needed to add some silence in the beginning of the final video, can't we just using the original audio if no silence needed at the beginning?
I think a solution to this problem might be using the original audio and add silence at the beginning and ending without altering the audio frequency or feeding in a preprocessed 44.1kHz audio in software like Audacity. Or doing some postprocess using other software by replacing the audio track.

**Comment by maRce10** [comment]
The only manipulation of the wave object happens [when adding silence](https://github.com/maRce10/dynaSpec/blob/52168e814a4f89dfb627902ab25b0da9cd9a9ee6/R/scrolling_spectro.R#L126).

**Comment by eldertiger** [comment]
> The only manipulation of the wave object in scrolling_spectro happens [when adding silence](https://github.com/maRce10/dynaSpec/blob/52168e814a4f89dfb627902ab25b0da9cd9a9ee6/R/scrolling_spectro.R#L126). There is no resampling at any point.
> 
> This is the code I used for creating the dynamic spectrogram:
> 
> ```
> ngh_wren <- read_wave("https://www.xeno-canto.org/518334/download")
> 
> custom_pal <- colorRampPalette( c("#2d2d86", "#2d2d86", reverse.terrain.colors(10)[5:10]))
> 
> scrolling_spectro(wave = ngh_wren, wl = 600, 
>     t.display = 3, ovlp = 95, pal = custom_pal, 
>     grid = FALSE, flim = c(2, 8), width = 700, 
>     height = 250, res = 100, collevels = seq(-40, 0, 5),
>     file.name = "../nightingale_wren.mp4", colbg = "#2d2d86", lcol = "#FFFFFFE6")
> ```
> 
> It seems like the issue is related to the reading/cutting of mp3 files (warbleR::read_wave uses tuneR::readMP3). There is no resampling involved.So its not really an issue of dynaSpec, but still something to be aware about.
> 
> In the mean time, it might be a better idea to convert mp3 files into wave using external software like audacity or sox.
> 
> thanks!

at line 481-483 of [when adding silence](https://github.com/maRce10/dynaSpec/blob/52168e814a4f89dfb627902ab25b0da9cd9a9ee6/R/scrolling_spectro.R#L126) 481-483, there is a resample, and this is  where the problem lies.
```
# resample to 44.1 kHz
  if (wave@samp.rate != 44100)
    wave <- seewave::resamp(wave = wave, f = wave@samp.rate, g = 44100, output = "Wave")
```

**Comment by maRce10** [comment]
It now resamples using ffmpeg: https://github.com/maRce10/dynaSpec/blob/505b441ac9b0197e8e4a9b7c056480b6aa43972e/R/scrolling_spectro.R#L483
thanks for reporting
