### ISSUE TITLE
errors on several functions from devtools::check

### ISSUE THREAD

**Issue by maRce10** [maRce10/dynaSpec#8]
Hi Matt, 

CRAN is asking us to submit a new version that deals with some silly issues about imports. However, I am getting several errors related to your functions. Here is the error log:

── R CMD check results ───────────────────────────────────────────────────────────────────────── dynaSpec 1.0.0 ────
Duration: 27s

> checking examples ... ERROR
  Running examples in ‘dynaSpec-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: paged_spectro
  > ### Title: Make a paged dynamic spectrogram similar to spectral display in
  > ###   Adobe Audition
  > ### Aliases: paged_spectro pagedSpectro pagedSpec
  > 
  > ### ** Examples
  > 
  > {
  + #show wav files included with dynaSpec
  + f <- list.files(pattern=".wav", full.names = TRUE, path = system.file(package="dynaSpec"))
  + 
  + femaleBarnSwallow<-prep_static_ggspectro(f[1],destFolder="wd",onlyPlotSpec = F, bgFlood=T)
  + paged_spectro(femaleBarnSwallow)
  + 
  + maleBarnSwallow<-prep_static_ggspectro(f[2],destFolder="wd",onlyPlotSpec = F, bgFlood=T,min_dB=-40)
  + paged_spectro(femaleBarnSwallow)
  + 
  + # Make a multipage dynamic spec of a humpback whale song
  + # Note, we're saving PNGs of our specs in the working directory; to add
  + # axis labels, we set onlyPlotSpec to F, and to make the same background
  + # color for the entire figure, we set bgFlood=T;
  + # The yLim is set to only go to 0.7kHz, where the sounds are for these big whales; 
  + #also applying an amplitude transform to boost signal.
  + #This is a longer file, so we're taking the first 12 seconds with crop=12
  + #xLim=3 means each "page" will be 3 seconds, so we'll have 4 dynamic spec pages that get combined
  + 
  + humpback <- prep_static_ggspectro(
  + "http://www.oceanmammalinst.org/songs/hmpback3.wav",savePNG=T,destFolder="wd",
  + onlyPlotSpec=F,bgFlood=T,yLim=c(0,.7),crop=12,xLim=3,ampTrans=3) 
  + 
  + #to generate multipage dynamic spec (movie), run the following
  + paged_spectro(humpback)
  + 
  + # see more examples at https://marce10.github.io/dynaSpec/
  + }
  Error in ggSpec(wav = prepped$newWav, soundFile = soundFile, segLens = prepped$segLens,  : 
    F used instead of FALSE
  Calls: prep_static_ggspectro -> ggSpec
  Execution halted

> checking dependencies in R code ... WARNING
  '::' or ':::' import not declared from: ‘fs’

> checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'is.url'
    ‘x’
  
  Undocumented arguments in documentation object 'prep_static_ggspectro'
    ‘plotLegend’ ‘onlyPlotSpec’ ‘specWidth’ ‘specHeight’ ‘...’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

> checking data for ASCII and uncompressed saves ... WARNING
    
    Note: significantly better compression could be obtained
          by using R CMD build --resave-data
                    old_size new_size compress
    canyon_wren.rda    505Kb    326Kb       xz

> checking R code for possible problems ... NOTE
  pagedSpec: no visible binding for global variable ‘xmin’
  pagedSpec: no visible binding for global variable ‘ymin’
  pagedSpec: no visible binding for global variable ‘xmax’
  pagedSpec: no visible binding for global variable ‘ymax’
  paged_spectro: no visible binding for global variable ‘xmin’
  paged_spectro: no visible binding for global variable ‘ymin’
  paged_spectro: no visible binding for global variable ‘xmax’
  paged_spectro: no visible binding for global variable ‘ymax’
  Undefined global functions or variables:
    xmax xmin ymax ymin

**Comment by drwilkins** [comment]
It looks like you fixed everything?? I don't see any errors when I run a build

**Comment by drwilkins** [comment]
should we close it or is there something I should address?

**Comment by maRce10** [comment]
I am still getting these errors:


── R CMD check results ────────────────────────────────────────────────────── dynaSpec 1.0.0 ────
Duration: 18.3s

> checking examples ... ERROR
  Running examples in ‘dynaSpec-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: paged_spectro
  > ### Title: Make a paged dynamic spectrogram similar to spectral display in
  > ###   Adobe Audition
  > ### Aliases: paged_spectro pagedSpectro pagedSpec
  > 
  > ### ** Examples
  > 
  > {
  + #show wav files included with dynaSpec
  + f <- list.files(pattern=".wav", full.names = TRUE, path = system.file(package="dynaSpec"))
  + 
  + femaleBarnSwallow<-prep_static_ggspectro(f[1],destFolder="wd",onlyPlotSpec = F, bgFlood=T)
  + paged_spectro(femaleBarnSwallow)
  + 
  + maleBarnSwallow<-prep_static_ggspectro(f[2],destFolder="wd",onlyPlotSpec = F, bgFlood=T,min_dB=-40)
  + paged_spectro(femaleBarnSwallow)
  + 
  + # Make a multipage dynamic spec of a humpback whale song
  + # Note, we're saving PNGs of our specs in the working directory; to add
  + # axis labels, we set onlyPlotSpec to F, and to make the same background
  + # color for the entire figure, we set bgFlood=T;
  + # The yLim is set to only go to 0.7kHz, where the sounds are for these big whales; 
  + #also applying an amplitude transform to boost signal.
  + #This is a longer file, so we're taking the first 12 seconds with crop=12
  + #xLim=3 means each "page" will be 3 seconds, so we'll have 4 dynamic spec pages that get combined
  + 
  + humpback <- prep_static_ggspectro(
  + "http://www.oceanmammalinst.org/songs/hmpback3.wav",savePNG=T,destFolder="wd",
  + onlyPlotSpec=F,bgFlood=T,yLim=c(0,.7),crop=12,xLim=3,ampTrans=3) 
  + 
  + #to generate multipage dynamic spec (movie), run the following
  + paged_spectro(humpback)
  + 
  + # see more examples at https://marce10.github.io/dynaSpec/
  + }
  Error in ggSpec(wav = prepped$newWav, soundFile = soundFile, segLens = prepped$segLens,  : 
    F used instead of FALSE
  Calls: prep_static_ggspectro -> ggSpec
  Execution halted

> checking dependencies in R code ... WARNING
  '::' or ':::' import not declared from: ‘fs’

> checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'is.url'
    ‘x’
  
  Undocumented arguments in documentation object 'prep_static_ggspectro'
    ‘plotLegend’ ‘onlyPlotSpec’ ‘specWidth’ ‘specHeight’ ‘...’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

> checking data for ASCII and uncompressed saves ... WARNING
    
    Note: significantly better compression could be obtained
          by using R CMD build --resave-data
                    old_size new_size compress
    canyon_wren.rda    505Kb    326Kb       xz

> checking R code for possible problems ... NOTE
  pagedSpec: no visible binding for global variable ‘xmin’
  pagedSpec: no visible binding for global variable ‘ymin’
  pagedSpec: no visible binding for global variable ‘xmax’
  pagedSpec: no visible binding for global variable ‘ymax’
  paged_spectro: no visible binding for global variable ‘xmin’
  paged_spectro: no visible binding for global variable ‘ymin’
  paged_spectro: no visible binding for global variable ‘xmax’
  paged_spectro: no visible binding for global variable ‘ymax’
  Undefined global functions or variables:
    xmax xmin ymax ymin
